- app/src/main/res/values-ja/localization.xml
- app/src/main/res/values-ja/strings.xml
> Import JA translations

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
- app/src/main/java/io/github/droidkaigi/confsched2017/di/FragmentComponent.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SearchActivity.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/DataBindingHelper.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchResultViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchViewModel.java
- app/src/main/res/anim/activity_fade_enter.xml
- app/src/main/res/anim/activity_fade_exit.xml
- app/src/main/res/drawable/ic_close_24.xml
- app/src/main/res/drawable/ic_description12_vector.xml
- app/src/main/res/drawable/ic_search_24_vector.xml
- app/src/main/res/drawable/ic_speaker_12dp_vector.xml
- app/src/main/res/drawable/ic_title_12_vector.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/view_search.xml
- app/src/main/res/layout/view_search_compat.xml
- app/src/main/res/layout/view_search_result.xml
- app/src/main/res/menu/menu_search.xml
- app/src/main/res/menu/menu_sessions.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_search.xml
https://github.com/DroidKaigi/conference-app-2017/issues/87
Created search page
> Created sessions search

- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
-
Use https://droidkaigi.github.io/2017/sessions.json
> Changed json url

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/MapFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SponsorsFragment.java
-
- replace `LayoutInflater.inflate` + `DataBindingUtil.bind`  to each `FragmentBinding.inflate`.
- this is a type safe and i prefer this.
-
> Use DataBinding inflate method

- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
#78 
Add API network feature for getting contributors
No Views have created yet.
> Add GithubService to list contributors

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java
- app/src/main/java/io/github/droidkaigi/confsched2017/util/AlarmUtil.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
NOTE: previous PR #92 has been destroyed because of my `git rebase` command ><
I have fixed feedbacks on the previous PR.
- #82 
- This PR provides first cut of notification feature.
- Show notification 10 minutes ago of session which user checks.
- Cancel notification when user unchecks session.
- By tapping the notification, app will launch.
- If user disables notification in setting screen, the notification will not show.
-
Before | After
:--: | :--:
> Notification feature

- app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRepository.java
- None
- Fix typo, sourse to source
-
Before | After
:--: | :--:
> Fix sourse to source

- README.md
- circle.yml
Report: https://codecov.io/gh/DroidKaigi/conference-app-2017
> Create test coverage analysis report on codecov.io

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- app/src/main/res/layout/fragment_session_detail.xml
-
Like an after party session, If topic color is null it is crash. 
So I set the default value.
and
if topic or room is null, I set View.GONE to session tag.
-
Before | After
:--: | :--:
> Fix crash when language resource is null 

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionsViewModel.java
- app/src/main/res/layout/fragment_sessions.xml
- #71 
- Show progress bar on loading sessions data
-
Before | After
:--: | :--:
> Show progress bar on loading sessons

- app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java
-
- Show head up notification if user enables it
-
Before | After
:--: | :--:
> Add head up notification

- app/build.gradle
- None
- Update Timber to v4.5.1
- https://github.com/JakeWharton/timber/blob/master/CHANGELOG.md#version-451-2017-01-20
- None
> Update Timber to v4.5.1

- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
#78 
Remove per_page options from API request.
https://github.com/DroidKaigi/conference-app-2017/pull/101#discussion_r99518814
N/A
> Remove ?per_page=100

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/LicensesFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/MapFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SponsorsFragment.java
- #131 
- Just add a constructor... 🙄 
none
none
> Add empty public constructor to Fragments

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java
- app/src/main/res/animator/raise.xml
- app/src/main/res/layout/view_session_cell.xml
- app/src/main/res/values/dimens.xml
- Add dynamic elevation offsets to session cell 
- If you like this pull request, Please merge this(This is not necessary to merge.)
- This provide material design Dynamic elevation offsets
https://material.io/guidelines/material-design/elevation-shadows.html#
- I adjust touch event (Change to a way closer to the native RecyclerView)
> Add dynamic elevation offsets to session cell

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- N/A
Changed ``SessionDetailViewModel.findSession()``'s return value ``Maybe<Session>`` to ``Completable``.
Because return value ``session`` does not used in ``SessionDetailFragment``.  ``Completable`` is fit to this case.
> Change return value Maybe to Completable in SessionDetailViewModel

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java
- app/src/main/res/layout/fragment_contributors.xml
- app/src/main/res/layout/view_contributor_cell.xml
- app/src/main/res/values/dimens.xml
- #78
- Implemented anyway
- Any comment is welcomed as I'm not so used to MVVM & Data Binding, Thanx!
-
Before | After
:--: | :--:
> Implement contributors view

- app/build.gradle
- app/src/androidTest/java/io/github/droidkaigi/confsched2017/ExampleInstrumentedTest.java
- app/src/main/java/io/github/droidkaigi/confsched2017/model/Topic.java
- connectedCheck failed on some build variants.
- updated failed test case.
- updated test libraries.
> fix error in connectedCheck

- circle.yml
- None
- Use copy command to remain apk files
- CircleCI build / https://circleci.com/gh/DroidKaigi/conference-app-2017/186
> Fixed master's failure due to missing apk files

- app/build.gradle
- app/licenses.yml
- app/src/main/java/io/github/droidkaigi/confsched2017/MainApplication.java
- This enables us to collect crash logs in DeployGate console
> Install DeployGate SDK

- circle.yml
- None
- Title says everything...
- None
> Cache dot-gradle dir

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/LicensesFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/IntentHelper.java
none
Since there were many places where intents were created using html url, I tried to create a helper class.
how is it?
https://github.com/DroidKaigi/conference-app-2017/pull/152#issuecomment-277914167
none
> Add intent helper

- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
- app/src/main/java/io/github/droidkaigi/confsched2017/model/Contributor.java
#148
Add anonymous contributors to contributors page
N/A
Before | After
:--: | :--:
> Handling anonymous contributors

- app/build.gradle
- app/licenses.yml
- app/src/main/assets/licenses.html
- app/src/main/res/layout/view_session_cell.xml
- circle.yml
- Apply constraint layout to view_session_cell.xml #139
- Introduce constraint layout
- Apply constraint layout to view_session_cell.xml
- Update licenses.yml
- Re-generate licenses.html
- https://developer.android.com/reference/android/support/constraint/ConstraintLayout.html
Before | After
:--: | :--:
> Apply constraint layout

- app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java
-
- Use @konifar 's icon for notification
-
Before | After
:--: | :--:
> Change notification icon

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java
- app/src/main/res/layout/fragment_contributors.xml
- https://github.com/DroidKaigi/conference-app-2017/issues/167
- Show progress bar on loading contributors data
-
Before | After
:--: | :--:
> Added loading to contributors page

- .idea/gradle.xml
- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
- app/src/main/java/io/github/droidkaigi/confsched2017/api/service/DroidKaigiService.kt
- app/src/main/java/io/github/droidkaigi/confsched2017/api/service/GithubService.kt
- app/src/main/java/io/github/droidkaigi/confsched2017/di/AppModule.java
- app/src/test/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClientTest.kt
- app/src/test/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsRepositoryTest.kt
- app/src/test/java/io/github/droidkaigi/confsched2017/util/DummyCreator.kt
- none
- extract DroidKaigiService and GithubService, and add these provider methods
- inject DroidKaigiService and GithuService to DroidKaigiClient
- add DroidKaigiClientTest
> Add DroidKaigiClientTest

- app/src/test/java/io/github/droidkaigi/confsched2017/util/DateUtilTest.kt
- none
- Remove Unneeded Semicolon in kt
> Remove Unneeded Semicolon in kt

- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/InfoRowView.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/SettingSwitchRowView.java
none
- Ref #158 
- Fix layout preview of InfoRowView on Android Studio
- and more simple
none 
Before | After
:--: | :--:
> Fix layout preview of InfoRowView on Android Studio

- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
- app/src/main/java/io/github/droidkaigi/confsched2017/api/service/GoogleFormService.kt
- app/src/main/java/io/github/droidkaigi/confsched2017/di/AppModule.java
- app/src/main/java/io/github/droidkaigi/confsched2017/model/SessionFeedback.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/feedbacks/SessionFeedbackRemoteDataSource.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/feedbacks/SessionFeedbackRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionFeedbackViewModel.java
- app/src/main/res/layout/fragment_session_feedback.xml
- app/src/test/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClientTest.kt
- #74 Create Session Feedback page
- Add session feedback button, dummy googleform url
N/A
N/A
I tried it. necessary everyone's follow. 🌵 🌵
> Add Session Feedback Button

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
-
- Fix the error message
-
Before | After
:--: | :--:
> fix-ContributorsFragment-error-message

- app/src/debug/java/io/github/droidkaigi/confsched2017/DebugApplication.java
-
log to logcat when logging with Timber(debug build only)
-
Before | After
:--: | :--:
> log to logcat with Timber

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
- #181
- Implements show number of contributors
- Remove unnecessary import
-
Before | After
:--: | :--:
> Implements show number of contributors

- app/build.gradle
- app/licenses.yml
- app/src/main/assets/licenses.html
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionDetailActivity.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionFeedbackActivity.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
None
Introduce [Fragment Creator](https://github.com/sys1yagi/fragment-creator).
It applied to Fragment with argument.
None
None
> Introduce fragment creator

- app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java
-
- Set large icon to notification
-
Before | After
:--: | :--:
> Set large icon to notification

- app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRemoteDataSource.java
- none
- remove unused import statements
> remove unused import statements

- app/src/main/AndroidManifest.xml
-
- Remove unnecessary permission
-
Before | After
:--: | :--:
> Remove unnecessary permission

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java
- None
- SearchFragment subscribed in `onCreateView`, but it was never disposed.
- Clear disposables in `onDestroyView`, and dispose all in `onDetach`.
- And I also destroy viewModel in `onDestroy` (Because it looks to be designed so).
-
Before | After
:--: | :--:
> Manage Disposable with lifecycle in SearchFragment

- app/src/test/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClientTest.kt
- none
- add DroidKaigi#submitSessionFeedback test
> add DroidKaigi#submitSessionFeedback test

- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/MainActivity.java
- none
- Return to session tab when back pressed on other tabs on MainActivity
- ref: Google+ app, Twitter app
- none
Before | After
:--: | :--:
> Return to session tab when back pressed on MainActivity

- app/src/main/java/io/github/droidkaigi/confsched2017/model/Session.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java
#219 
* Add new session type `DINNER`
* After party cell col span should be 6 
-
Before | After
:--: | :--:
> Make after party col span 6

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionsViewModel.java
- app/src/main/res/layout/view_session_cell.xml
#231
* Add long tap to check/uncheck session
* Use Timber instead of Log
-
Before | After
:--: | :--:
> Add long tap to check/uncheck session

- README.md
- None
- I think, I found unnecessary `)` in https://github.com/DroidKaigi/conference-app-2017#contributing . So I delete that.  
If that is not mistake, so sorry.
- None
Before | After
:--: | :--:
> Fix label in README.md

- app/build.gradle
- 0.3.0 is in beta so I picked up the latest stable version
> FlexBox Layout 0.2.5

- app/build.gradle
- app/lint.xml
- app/src/main/java/io/github/droidkaigi/confsched2017/util/LocaleUtil.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/BottomNavigationViewHelper.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java
-
* Fix lint check `LogNotTimber`
* Fix lint check `TimberArgCount`
* Make LogNotTimber severity error
-
Before | After
:--: | :--:
> Fix lint for logging

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- none
- Fix session detail language check condition
- none
Before | After
:--: | :--:
> Fix session language in detail page

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/MapFragment.java
- app/src/main/res/drawable/ic_nav_24_vector.xml
- app/src/main/res/menu/menu_map.xml
- app/src/main/res/values/strings.xml
Issue :#262
Will put a screen shot later :)
> Add start navigation button as options menu

- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/DataBindingHelper.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchResultViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchViewModel.java
- app/src/main/res/layout/view_search_result.xml
- app/src/main/res/values/dimens.xml
- #232 
- Add check mark to the left side of session title
- But marks are not reload when comming back from session detail.
(Could you help me? @kwmt 🙇 )
> Add check mark to SearchResult

- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
- app/src/main/java/io/github/droidkaigi/confsched2017/util/LocaleUtil.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionDetailActivity.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionFeedbackActivity.java
- None
- Delete unused import
- None
Before | After
:--: | :--:
> Delete unused import

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- app/src/main/res/values/strings.xml
- #230 
- Show snackbar when session is checked or unchecked
- 
Before | After
:--: | :--:
> Show snackbar if session is checked or unchecked

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java
- #232 
-  Search result scree  can  reload when coming back from session detail.
- https://github.com/DroidKaigi/conference-app-2017/pull/264
Before | After
:--: | :--:
I notice session title is overlapping with speaker image.
> add reload when comming back from session detail

- app/src/main/java/io/github/droidkaigi/confsched2017/MainApplication.java
- app/src/main/java/io/github/droidkaigi/confsched2017/util/AppShortcutsUtil.java
- app/src/main/res/drawable/ic_shortcut_search_24_vector.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
- None.
- Add App Shortcuts with dynamic shortcuts, because it's difficult to handle dynamic package name.
- http://qiita.com/kuwata/items/c4cd8f6f691c1b4996d8#staticshortcuts%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E3%81%84%E3%81%A6%E3%83%93%E3%83%AB%E3%83%89%E6%99%82%E3%81%AB%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E5%90%8D%E3%82%92%E5%8B%95%E7%9A%84%E3%81%AB%E5%A4%89%E6%9B%B4%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%A8%E3%81%8D%E3%81%AE%E5%AF%BE%E5%BF%9C
- https://developer.android.com/guide/topics/ui/shortcuts.html
Before | After
:--: | :--:
> Introduce App Shortcuts

- app/src/main/res/layout/view_sponsor_cell.xml
- app/src/main/res/layout/view_sponsorship_cell.xml
- app/src/main/res/values/dimens.xml
#279 
* Adjust sponsors page layout
-
Before | After
:--: | :--:
> Adjust sponsors page layout

- app/src/main/res/values-ja/strings.xml
- Just I found
- Add translated japanese strings.
Before | After
:--: | :--:
> Add translated japanese strings.

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/InformationViewModel.java
> Fix tiny typo 📝

- app/src/main/res/values-ja/strings.xml
#266
* Remove unused string (Fix lint errors `ExtraTranslation`)
I sent PR from the same branch name last year!
https://github.com/konifar/droidkaigi2016/pull/125
Before | After
:--: | :--:
> Remove unused strings

- app/build.gradle
- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/FeedbackRankingView.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionFeedbackViewModel.java
- app/src/main/res/color/feedback_circle_text.xml
- app/src/main/res/drawable/bg_feedback_circle.xml
- app/src/main/res/layout/fragment_session_feedback.xml
- app/src/main/res/layout/view_feedback_ranking.xml
- app/src/main/res/layout/view_feedback_ranking_item.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles_base.xml
- app/src/main/res/values/styles_feedback.xml
https://github.com/DroidKaigi/conference-app-2017/issues/74
- To prepare to implement feedback page, I created `FeedbackRankingView`.
- Added `FeedbackRankingView` to `SessionFeedbackFragment` as sample.
> Created FeedbackRankingView

- app/src/test/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClientTest.kt
- app/src/test/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModelTest.kt
- None
- Change getter and setter to Kotlin syntax.
- https://kotlinlang.org/docs/reference/properties.html#declaring-properties
- None
> Use property access syntax

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SponsorshipViewModel.java
None
Use method references in stream api processing.
None
None
> Use method references.

- app/src/main/java/io/github/droidkaigi/confsched2017/repository/contributors/ContributorsRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRemoteDataSource.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionFeedbackViewModel.java
- None
map operator purpose is to transform items.
In this case, Using doOnSuccess is better.
- [ReactiveX \- Map operator](http://reactivex.io/documentation/operators/map.html)
- [ReactiveX \- Single](http://reactivex.io/documentation/single.html)
Before | After
:--: | :--:
> Change map to doOnSuccess

- app/src/main/res/layout/activity_contributors.xml
- app/src/main/res/layout/activity_licenses.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/activity_session_detail.xml
- app/src/main/res/layout/activity_session_feedback.xml
- app/src/main/res/layout/activity_sponsors.xml
- app/src/main/res/layout/fragment_session_detail.xml
none
I fix wrong "tools:context" in layout.xml.
Also add to layout.xml of Activity which did not have "tools:context".
none
There was no change on the Android Studio preview... 🙄
> Fix "tools:context" in layout.xml

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java
- Add my session from sessions page with long clicking session cell, alarm was not fired.
-
-
Before | After
:--: | :--:
|
> Register alarm when long clicking on session cell

- app/src/main/res/layout/view_sponsor_cell.xml
- none
- I was going to add ripple effect in sponsor logo.
- none
Before | After
:--: | :--:
> Fix ripple effect in sponsor logo

- app/src/main/assets/json/sponsors.json
- app/src/main/assets/json/sponsors_en.json
:tada: welcome new sponsor :tada:
- https://droidkaigi.github.io/2017/#sponsors
Before | After
:--: | :--:
> add new sponsor

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/droidkaigi/confsched2017/di/FragmentComponent.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/MySessionsActivity.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/MySessionsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/MySessionViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/MySessionsViewModel.java
- app/src/main/res/layout/activity_my_sessions.xml
- app/src/main/res/layout/fragment_my_sessions.xml
- app/src/main/res/layout/view_my_session.xml
- app/src/main/res/menu/menu_sessions.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
- none
**I created my session list page, but if you don't need, please close this pull request.**
- I think I want to see my session list page. Because when I saved many sessions, I didn't know what session I saved.
- In this page, I want to check WHEN, WHERE, WHO and WHAT.
If you will merge, I couldn't decide about some points below:
- my session list layout design.
- the way to display this page (now  from menu of session page)
- description text if the list is empty
- 
Before | After
:--: | :--:
> Create My Session List Page

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/MySessionsViewModel.java
> Fix a mistake of copy-and-paste

- app/src/main/java/io/github/droidkaigi/confsched2017/util/LocaleUtil.java
- #342 
- Fixed it because configuration is overwrite.
- none
> Fix configuration overwrite

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/MySessionsViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionsViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SponsorshipViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SponsorshipsViewModel.java
- none
- Replace `collect(Collectors.toList())` to `Stream.toList()`.
- `Stream.toList()` which can be much faster and convenient than `collect(Collectors.toList())`!!
- This implementation does not call `collect(Collectors.toList())`, so it can be faster by reducing method calls.
- https://github.com/aNNiMON/Lightweight-Stream-API/releases/tag/v1.1.5
- http://static.javadoc.io/com.annimon/stream/1.1.5/com/annimon/stream/Stream.html#toList--
> Replace collect(Collectors.toList()) to Stream.toList().

- app/src/main/java/io/github/droidkaigi/confsched2017/util/AppUtil.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/LicensesFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SponsorsFragment.java
- none
- I was going to add ChromeCustomTabs and fix to open web page.
- I'm super super sorry to do not use awesome [helper](https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/IntentHelper.java) developed by our FRIEND. 😿  
- https://developer.chrome.com/multidevice/android/customtabs
Before | After
:--: | :--:
> Add ChromeCustomTabs

- README.md
none
- `are bind` -> `are bound`
- Change location of `or`
none
none
> Fix little grammar mistakes

- app/src/test/java/io/github/droidkaigi/confsched2017/repository/contributors/ContributorsLocalDataSourceTest.kt
- app/src/test/java/io/github/droidkaigi/confsched2017/repository/contributors/ContributorsRemoteDataSourceTest.kt
- app/src/test/java/io/github/droidkaigi/confsched2017/repository/contributors/ContributorsRepositoryTest.kt
- app/src/test/java/io/github/droidkaigi/confsched2017/util/RxTestSchedulerRule.kt
None
- Add more tests to `ContributorsRepositoryTest`
- Add `ContributorsLocalDataSourceTest` and `ContributorsRemoteDataSourceTest`
> Add tests for ContributorsRepository and data sources

- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/OverScrollLayout.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- none
- Fix some PR comment from @jmatsu #359
- 112fd7b : Swap if statement condition orde https://github.com/DroidKaigi/conference-app-2017/pull/359#pullrequestreview-22684993
- 915a451 : Rename constant value https://github.com/DroidKaigi/conference-app-2017/pull/359#pullrequestreview-22685493
- 33614bb : Use Rect instead of Point and primitive integer https://github.com/DroidKaigi/conference-app-2017/pull/359#pullrequestreview-22685234
- 2ad1552 : Simplify AppBarLayout expanded/collapsed check https://github.com/DroidKaigi/conference-app-2017/pull/359#pullrequestreview-22686021
- fca3292 : Check callback is null or not https://github.com/DroidKaigi/conference-app-2017/pull/359#pullrequestreview-22685520
- 0d77f42 : Fix duplicate view translation when AppBar is null
- …
> Fix some PR comment

- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/ParticlesAnimationView.java
- https://github.com/DroidKaigi/conference-app-2017/pull/366
- Because create new instance every time.
- none
Thank for @eneim !
I learned a lot. 😇  
Is this OK?
> Change for statement.

- gradle/wrapper/gradle-wrapper.properties
- Full Release Note: https://docs.gradle.org/current/release-notes.html
> Use Gradle 3.4

- app/src/main/res/values-ja/strings.xml
- none
- for Japanese 🇯🇵 
- none
- none
> Translate messages when check/uncheck the session

- app/build.gradle
- circle.yml
- It's stable now!!
- Full release note: https://sites.google.com/a/android.com/tools/recent/constraintlayout10isnowavailable
> :tada: Constraint Layout 1.0.0

- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/DataBindingHelper.java
- #383 
- Show icon of speakers 🎉
-
Before | After
:--: | :--:
> Fixed #383

- app/build.gradle
- app/src/main/java/io/github/droidkaigi/confsched2017/api/service/DroidKaigiService.java
- app/src/main/java/io/github/droidkaigi/confsched2017/di/AppModule.java
- app/src/main/java/io/github/droidkaigi/confsched2017/model/Speaker.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/DataBindingHelper.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- app/src/main/res/layout/fragment_session_detail.xml
- app/src/test/java/io/github/droidkaigi/confsched2017/model/SpeakerTest.kt
https://github.com/DroidKaigi/conference-app-2017/pull/385
- Refactored speaker image url binding.
- Originally the image url is converted in `DataBindingHelper` class.
- But I think this should be converted in `Speaker` class.
I'll upload later.
> Refactored speaker image url binding

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/InformationViewModel.java
#77
Add link for questionnaire page
This is temporary solution for the questionnaire page.
-
Before | After
:--: | :--:
> Add Questionnaire link to Information page

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
- app/src/main/java/io/github/droidkaigi/confsched2017/api/service/GoogleFormService.java
- app/src/main/java/io/github/droidkaigi/confsched2017/di/FragmentComponent.java
- app/src/main/java/io/github/droidkaigi/confsched2017/model/Questionnaire.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/feedbacks/QuestionnaireRemoteDataSource.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/feedbacks/QuestionnaireRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/QuestionnaireActivity.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/QuestionnaireRadioView.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/QuestionnaireView.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/QuestionnaireFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/Navigator.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/InformationViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/QuestionnaireViewModel.java
- app/src/main/res/layout/activity_questionnaire.xml
- app/src/main/res/layout/fragment_questionnaire.xml
- app/src/main/res/layout/view_questionnaire.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_questionnaire.xml
- build.gradle
❗️ ❗️ ❗️ THIS PR IS TO `questionnaire`❗️ ❗️ ❗️ 
#77
Create questionnaire page
-
Before | After
:--: | :--:
> [WIP] Questionnaire page

- app/src/main/java/io/github/droidkaigi/confsched2017/service/helper/OverlayViewManager.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/DebugOverlayView.java
- Reduce redundant context hierarchy, bring less complexity
- No functional changes!
> Simplify context hierarchy

- build.gradle
-
- Android Studio 2.3 released!!! 
- http://android-developers.googleblog.com/2017/03/android-studio-2-3.html
Before | After
:--: | :--:
> Android Studio 2.3 released!

- app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionDetailActivity.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/Navigator.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/MySessionViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchResultViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java
- #352 
- Fixed behavior of UP button in session detail page
- If it comes from search page, UP button navigates to search page.
- If it comes from my sessions page, UP button navigates to my sessions page.
- Otherwise, UP button navigates to main page.
- http://qiita.com/kobakei/items/ae1a6d2062f34d3f6771
Before | After
:--: | :--:
> Fix session detail UP button

- app/src/main/java/io/github/droidkaigi/confsched2017/model/SessionFeedback.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/feedbacks/SessionFeedbackLocalDataSource.java
- app/src/main/java/io/github/droidkaigi/confsched2017/repository/feedbacks/SessionFeedbackRepository.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/Navigator.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionFeedbackViewModel.java
- app/src/main/res/layout/fragment_session_feedback.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/github/droidkaigi/confsched2017/model/SessionFeedbackTest.kt
- https://github.com/DroidKaigi/conference-app-2017/pull/402
- Handle network error.
- Limit submission terms.
> Session feedback rest tasks

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/MySessionViewModel.java
- None
- Speaker image didn't display on Mysession list.
-
Before | After
:--: | :--:
| <img src="https://cloud.githubusercontent.com/assets/1450486/23732638/937f5fb6-04b7-11e7-9a98-3e7af7bc5788.png" width="300" /> | <img src="https://cloud.githubusercontent.com/assets/1450486/23732671/c07fb9f2-04b7-11e7-9d80-6408ca901ac0.png" width="300" /> |
> Fixed speaker image icon on mysession

- app/lint.xml
- app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/BottomNavigationViewHelper.java
- #266
- Fix lint errors Restricted Api.
- Add `SuppressWarnings` annotation to BottomNavigationViewHelper.
- Exclude path `build/generated` from lint.
- None
Before | After
:--: | :--:
> Fix lint errors Restricted Api

- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java
- app/src/main/res/layout/fragment_session_detail.xml
- #415
- remove person icon in after party cell
-
Before | After
:--: | :--:
> Remove person icon in after party cell

- app/build.gradle
https://github.com/DroidKaigi/conference-app-2017/issues/423
💪
> Release 1.1.0

- app/src/main/res/layout/fragment_session_detail.xml
- app/src/main/res/layout/view_my_session.xml
- app/src/main/res/layout/view_search_result.xml
- app/src/main/res/values/dimens.xml
-
💪 
-
Before | After
:--: | :--:
> Refactoring icon dimens

- app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java
- #425 
- NPE occurred, when activity is recreated.
- http://ja.stackoverflow.com/a/6196
Before | After
:--: | :--:
> Fixed because NPE occurred, when activity is recreated.

- app/src/main/res/drawable/circle_border_grey200.xml
- app/src/main/res/drawable/rectangle_border_grey200.xml
- app/src/main/res/values/dimens.xml
-
**300!!!!!!!!!!!!!!!!** 💪 💪 💪 💪 💪 
-
Before | After
:--: | :--:
> Replace user_image_border with border_1dp
