app/build.gradle
- N/A
- Use [Resolution Strategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) to keep build.gradle simple
- N/A
- N/A
=> use regolutionStorategy instead of on-demand exclude

.idea/icon.png
- N/A
- `.idea/icon.png` is shown in the IntelliJ IDEA welcome window (see the attached screenshot)
- N/A
=> set .idea/icon.png to show the icon in Android Studio start window

app/build.gradle
-
- Move the position of `apply plugin: 'com.google.gms.google-services'` to the bottom of build.gradle
- this is required for Firebase to work properly
- https://firebase.google.com/docs/android/setup?hl=en
Before | After
:--: | :--:
=> Move the position of google-services plugin at the bottom

app/build.gradle, app/licenses.yml, app/src/main/AndroidManifest.xml, app/src/main/assets/licenses.html, app/src/main/java/io/github/droidkaigi/confsched2017/di/ActivityComponent.java, app/src/main/java/io/github/droidkaigi/confsched2017/di/FragmentComponent.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/LicensesActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/LicensesFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/DataBindingHelper.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/LicensesViewModel.java, app/src/main/res/layout/activity_licenses.xml, app/src/main/res/layout/fragment_licenses.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml, build.gradle
- Create licence page #79
- Add open source licenses page using cookpad license plugin.
- https://github.com/cookpad/license-tools-plugin
Before | After
:--:|:--:
=> Add license page

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/InformationViewModel.java, app/src/main/res/layout/fragment_information.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
-
"licence" and "license" are mixed in project. I think those should be unified.
- [Licence vs\. License: What’s the Difference? \- Writing Explained](http://writingexplained.org/licence-vs-license-difference)
Before | After
:--: | :--:
=> Replace "licence" with "license"

app/build.gradle, app/licenses.yml
-
- grouping licenses in licenses.yml 
- I think grouping licenses is better than skipping other except main.
- add checklicenses-task in check-task.
-
I confirmed generated html is not changed.
=> grouping licenses in licenses.yml

app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/TouchlessTwoWayView.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java, app/src/main/res/layout/fragment_sessions.xml
- Not exact one, but related with https://github.com/DroidKaigi/conference-app-2017/issues/72
- Enable diagonal scroll on the session list to use motion event dispatch/simulate process.
- You couldn't see any effects when pressed a session long
- None
=> Enable diagonal scroll on the session list without using custom layoutmanager

app/src/main/java/io/github/droidkaigi/confsched2017/model/Session.java
- None
When transitioning from SessionsFragment to SessionDetailFragment, language tag on SessionDetailFragment unfortunately all became 'English'.
Fixed this tag to become the language of the target session.
- None
Before | After
:--: | :--:
=> Fix language tag on SessionDetail

app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java, app/src/main/res/layout/view_session_cell.xml
- None
- AfterParty's language text is empty, I add default value to 'languageId' in SessionViewModel.
-
Before | After
:--: | :--:
=> add languageId default value

app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/TopicColor.java
-
`TopicColor` contains styles, colors, and so on. 
I think it should not be a model, but a view-model. In fact `TopicColor` is used only by some view-models.
This PR just moves `TopicColor` into the `viewmodel` package :)
-
Nothing changed, because of just a refactoring.
=> move TopicColor to viewmodel

app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsLocalDataSource.java, app/src/test/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsRepositoryTest.kt
=> add MySessionsRepositoryTest

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorViewModel.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java
#78 
* Create `ContributorViewModel` for handling single grid.
* Use `List<ContributorViewModel>`
* Remove callback from `ContributorsViewModel`
https://github.com/DroidKaigi/conference-app-2017/pull/122#discussion_r99580590
N/A
=> Convert to ContributorViewModel

app/src/main/AndroidManifest.xml, app/src/main/res/xml/network_security_config.xml
- Not an issue, but https is more secure and SEO-friendly comparing to http.
- All outbound network traffic originated from the app are bounded in HTTPS. App can no longer access by http.
-https://developer.android.com/reference/android/security/NetworkSecurityPolicy.html#isCleartextTrafficPermitted()
- https://developer.android.com/training/articles/security-config.html#CleartextTrafficPermitted
No change in images.
=> Add security config(Enforcing https)

circle.yml
-
By saving the APK in Circle CI's artifact, we can download and try it easily just with a mobile phone (without PC for build), just by browsing the file like below:
With this feature, we can try the APK even during commute in the train :)
It would be helpful for some people in reviewing and discussing the Pull Requests.
-
Nothing changed.
=> save APK into CircleCI's artifact

app/build.gradle, build.gradle
I have updated gradle-retrolambda 3.4.0 -> 3.5.0. This allows us to remove `retrolambdaConfig` setting as the default retrolambda version of gradle-retrolambda 3.5.0 is `2.5.0`.
- gradle-retrolambda changelog: https://github.com/evant/gradle-retrolambda/blob/master/CHANGELOG.md#350
- retrolambda changelog: https://github.com/orfjackal/retrolambda#retrolambda-250-2017-01-22
=> Update Retrolambda 3.4.0 -> 3.5.0 and remove retrolambdaConfig

app/src/main/java/io/github/droidkaigi/confsched2017/util/ViewUtil.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java, app/src/main/res/layout/fragment_sessions.xml
- https://github.com/DroidKaigi/conference-app-2017/issues/128
- It seems twoway-view cannot recognize recycle-span correctly.
- I fixed RecyclerView's height with modifying layout definitions, and then confirmed this can be applied as a workaround of this problem.
- None
Before | After
:--: | :--:
Just in case, for API 23
=> Applied a workaround to fix wrong layout when running on api 16

app/build.gradle, build.gradle
- None
- ./gradlew dependencyUpdates → /app/build/dependencyUpdates/report.txt
- https://github.com/ben-manes/gradle-versions-plugin
:app Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest milestone version:
- com.android.support:animated-vector-drawable:25.1.1
- com.android.support:appcompat-v7:25.1.1
- com.squareup.assertj:assertj-android:1.1.1
- com.android.databinding:baseLibrary:2.2.3
- uk.co.chrisjenx:calligraphy:2.2.0
- com.android.databinding:compiler:2.2.3
- com.squareup.retrofit2:converter-gson:2.1.0
- com.android.support:customtabs:25.1.1
- com.android.support:design:25.1.1
- com.android.support.test.espresso:espresso-core:2.2.2
- …
=> Add  ./gradlew dependencyUpdates

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java
none
There is no action even if you click on Contributor item.
So we decided to open the url passed in the browser.
- https://github.com/DroidKaigi/conference-app-2017/issues/78
- https://github.com/DroidKaigi/conference-app-2017/pull/138
none
=> Add open link when contoributors item

app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsLocalDataSource.java, app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRemoteDataSource.java, app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRepository.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java, app/src/test/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRepositoryTest.kt
Add test for SessionsRepository #96
- Add SessionsRepositoryTest and a first test for hasCacheSessions(). 	27ce6ac
- Move subscribeOn and observeOn calls from the data source to where we actually use each Observable. 102e6a9
- Add tests for `SessionsRepository.findAll()`. 102e6a9
- Add hasSession(int) and test.			5ef2fd2
- Fix SessionsRemoteDataSource.find(int, String).  d36bfae
- Add tests for find(int, String). bf8d36d
None
None
=> Add unit test for sessions repository

app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsLocalDataSource.java
None
Remove unnecessary thread control.
Since updateAllAsync() in SessionsLocalDataSource has no subscriber, I think that obserbeOn() is unnecessary.
None
None
=> Remove unnecessary thread control.

app/src/main/AndroidManifest.xml, app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionDetailActivity.java
- #151 
- Change the launch activity on notification tap from `MainActivity` to `SessionDetailActivity`.
- `SessionDetailActivity` always navigates to `MainActivity` when "up button" is clicked.
- [Providing Up Navigation | Android Developers](https://developer.android.com/training/implementing-navigation/ancestral.html)
By the above Android Developers guideline, we should use `NavUtils#shouldUpRecreateTask` to check if `MainActivity` has been added to backstack, however the method always returns false as far as I worked.
So I now use custom action of `Intent` to check it.
Please tell me a good way for handling "up button" click event if you know.
Thanks.
=> Change launch activity on notification tap

app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/SettingSwitchRowView.java, app/src/main/res/layout/view_setting_switch_row.xml
-`fragment_settings.xml`'s layout preview was not drawn correctly causes constructor of `SettingsSwitchRowView`.
-
-
Before | After
:--: | :--:
=> Fix layout preview of fragment_settings.xml on Android Studio

app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java, app/src/main/java/io/github/droidkaigi/confsched2017/util/AlarmUtil.java
-
- Show group notification
- e.g. If user check 4 sessions which start at 3/9 10:40, 4 notifications will be shown but they should be summarized like Gmail app.
- Set unique ID (=session ID) to PendingIntent and Notification not to override other PendingIntent and Notification objects.
-
Before | After
:--: | :--:
The second screen shot is captured when user expand group notification.
=> Group notification

app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java
N/A
Previously, we delete the query `per_page` #121 
But I believe this option is mandatory to display more than 30 contributors
N/A
Before | After
:--: | :--:
=> Add per_page query since github api only returns 30 contributors by default

app/src/main/AndroidManifest.xml, app/src/main/res/values/themes.xml
- #162 
- Fix `AppTheme.Translucent` style.
- Apply `AppTheme.Translucent` to `SearchActivity`.
-
Before | After
:--: | :--:
=> Change search page background to translucent.

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java
-
- When returning from SessionDetailActivity, the date is reset.(Please see screenshot. The day has changed from `3月10日` to `3月9日`.)
-
Before | After
:--: | :--:
=> Fixed the date is reset When returning from SessionDetailActivity

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java
- #176
- Use "colorPrimaryDark" matching the primary color on the session detail page
-
Before | After
:--: | :--:
=> Change status bar color when contents scrolled in session detail page

app/src/main/res/values/styles_information.xml
- #182 
- Change information section title smaller
-
Before | After
-: | :--:
=> Change information section title smaller

circle.yml
- N/A
- Android SDK tools provides [sdkmanager(1)](https://developer.android.com/studio/command-line/sdkmanager.html) that manages all the Android SDK components including `constraint-layout`
- `wget constraint-layout` sucks. Use sdkmanager instead.
- There are some circle-ci tweaks to make the build more stable
=> use sdkmanager(1) instead of downloading compnents with wget(1)

circle.yml
- N/A
- Skip redundant tests  in CI
- `./gradlew check` does `lint`, `test`, and `assemble` for **all** the variants, but we need just a few
- We just need `assembleProductionDebug` executed above
- Because `jacocoTestReportDevelop` includes `app:testDevelopDebugUnitTest` , it is considered enough as unit testing
=> skip redundant tests; jacocoTestReportDevelop includes app:testDevelopDebugUnitTest

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java, app/src/main/res/layout/fragment_sessions.xml
- Empty txt_date can be seen for a moment, so make it invisible.
Before | After
:--: | :--:
=> Empty txt_date can be seen for a moment, so make it invisible.

circle.yml
- None
- Stopped running `check` task, then CircleCI doesn't run `checkLicense` too.
- So I added `checkLicense` to test tasks of CircleCI.
- https://github.com/DroidKaigi/conference-app-2017/pull/195#discussion_r99980201
=> Added checkLicenses to test tasks

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- Open SessionDetailActivity, the app crashes extremely rarely.
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.github.droidkaigi.confsched2017.develop.debug, PID: 24060
android.content.res.Resources$NotFoundException: String resource ID #0x0
at android.content.res.Resources.getText(Resources.java:299)
at android.widget.TextView.setText(TextView.java:4132)
at io.github.droidkaigi.confsched2017.databinding.FragmentSessionDetailBinding.executeBindings(FragmentSessionDetailBinding.java:269)
at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355)
at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:172)
at android.databinding.ViewDataBinding$5.onViewAttachedToWindow(ViewDataBinding.java:142)
at …
```
=> Fix crash when SessionDetailFragment inflated before loadSession completed

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java
- #205
This reason is fired clicked event in RecyclerView because position X does not changes between ACTION_DOWN and ACTION_UP.
I send cancelling motion event when horizontal scrolling.
But, I can't resolve when start scrolling with "long tapped" above session cell.
In this case, still session detail page shown when scroll ended.
This fix is inspired from ``RecyclerView.java``.
- https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/recyclerview/src/android/support/v7/widget/RecyclerView.java#1927
Before | After
:--: | :--:
=> Fix unnecessary page shown when little horizontal scrolled

app/src/main/res/values/styles_base.xml
- #163
- Parent style for Toolbar should be ThemeOverlay.AppCompat.XX
- Specify @color/white as colorControlActivated for text selection handle
-
Before | After
:--: | :--:
- I think ThemeOverlay.AppCompat.Dark.ActionBar is more appropriate. But this style change searchViewStyle, so it's up to you.
- This is a screenshot when use ThemeOverlay.AppCompat.Dark.ActionBar as parent of ToolbarTheme. Underline and Search Icon disappear.
=> Change parent style for Toolbar to ThemeOverlay.AppCompat.Dark

app/src/main/java/io/github/droidkaigi/confsched2017/util/AlarmUtil.java
-
- From Android M, doze / app standby are introduced, which delay alarm manager.
- To avoid such case, I use `setAndAllowWhileIdle` instead of `set` on Android M and later.
- https://developer.android.com/training/monitoring-device-state/doze-standby.html?hl=ja#assessing_your_app
- https://developer.android.com/reference/android/app/AlarmManager.html?hl=ja
- `This type of alarm must only be used for situations where it is actually required that the alarm go off while in idle -- a reasonable example would be for a calendar notification that should make a sound so the user is aware of it.`
Before | After
:--: | :--:
=> Enable alarm even if device is doze mode

app/src/main/java/io/github/droidkaigi/confsched2017/repository/contributors/ContributorsRepository.java, app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsLocalDataSource.java, app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsRepository.java, app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRepository.java
- None
- remove unnecessary try catch in SingleOnSubscribe.subscribe() and MaybeOnSubscribe.subscribe(), because MaybeCreate and SingleCreate call onError() when Exception throws in subscribe().
```
public final class SingleCreate<T> extends Single<T> {
final SingleOnSubscribe<T> source;
public SingleCreate(SingleOnSubscribe<T> source) {
this.source = source;
}
@Override
protected void subscribeActual(SingleObserver<? super T> s) {
Emitter<T> parent = new Emitter<T>(s);
s.onSubscribe(parent);
try {
source.subscribe(parent);
} catch (Throwable ex) {
Exceptions.throwIfFatal(ex);
parent.onError(ex);
}
}
...
}
```
=> remove unnecessary try catch in SingleOnSubscribe.subscribe() 

app/src/main/java/io/github/droidkaigi/confsched2017/repository/contributors/ContributorsRepository.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java, app/src/main/res/layout/fragment_contributors.xml
-
- This project is frequently contributed so I added swipe to refresh to contributors page.
- When user swipes to refresh, contributors will be fetched from GitHub API even if data is cached.
-
Before | After
:--: | :--:
=> Add swipe refresh to contributors

app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java
Session A's notification notified, tap it and move to A's detail.
Next, session B's notification notified, tap it and move to A, not B.
- Extra data of PendingIntent used in notification was not updated.
-
Before | After
:--: | :--:
=> Fix move to correct session's detail from notifications

app/src/debug/java/io/github/droidkaigi/confsched2017/di/HttpClientModule.java
-
- When I open stetho, GitHub API fails.
- Stetho doc says to use `addNetworkInterceptor`.
- http://facebook.github.io/stetho/#integrations
Before | After
:--: | :--:
=> Fix stetho interceptor

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/MainActivity.java
- #235 
-  When I hit the BottomNavigationView Item continuously at the same time, it would often cause this below. (screenshot)
- https://developer.android.com/reference/android/app/FragmentManager.html
- http://qiita.com/tomoima525/items/d10fda955a97c265f338
Before | After
:--: | :--:
=> execute pending transaction before the next fragment transaction starts

app/src/main/java/io/github/droidkaigi/confsched2017/model/Session.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java, app/src/main/res/drawable-v21/clickable_purple.xml, app/src/main/res/drawable/clickable_purple.xml
- #161
- Highlight ongoing sessions. It checks every session with `new Date()` but I don't have any good pattern for this and implemented such roughly as-is.
- It seems `Session.Type#toString()` is overriden just for `equals` check.  
If `Session.type` is `Type type`, `Session#isBreak()` will be `type == Type.BREAK`.
idk why `Session.type` is not `Type` (im not familiar with orma, adapting enum brings complexity?) so just make `Type` to have its own equality method using `name().equalsIgnoreCase()`. I will revert this change as you like (eg. json should strictly declare lowercase for `type` key. this change will be breaking).
Before | After
:--: | :--:
=> Highlight ongoing sessions

app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java
- Session language in detail page is always English #243
- Change session id letter case from upper to small, because `LocaleUtil` constant value is lower case.
- https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/util/LocaleUtil.java
Before | After
:--: | :--:
=> Fix session language decision in SessionDetailViewModel

app/src/main/res/layout/fragment_session_detail.xml
In session detail screen, back key color is not white.
- Apply theme to Toolbar to set standard colors of this app.
Before | After
:--: | :--:
=> Apply style to Toolbar of session detail screen to change back button color.

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/BaseActivity.java
- #246 
- Leakcanary reports leaking Activity in Debot. It seems SensorManager might being hold Activity if created with `activityContext.getSystemService()` 
https://github.com/tomoima525/debot/blob/master/debot/src/main/java/com/tomoima/debot/Debot.java#L57 
I think it can be solved with some ways.
1. Debot uses `context.getApplicationContext().getSystemService()`
2. Passing `getApplicationContext()` by ourselves.
3. Move calling `debot#allowShake()` to `onResume()`
4. AOSP fix this.
I did quick fix with 2 and not detected leak currently. But not much tested, would you check this?
=> Use application context for sensor

app/src/debug/java/io/github/droidkaigi/confsched2017/debug/NotificationStrategy.java, app/src/main/java/io/github/droidkaigi/confsched2017/MainApplication.java, app/src/main/java/io/github/droidkaigi/confsched2017/pref/DefaultPrefsSchema.java, app/src/main/java/io/github/droidkaigi/confsched2017/util/AlarmUtil.java, app/src/release/java/io/github/droidkaigi/confsched2017/debug/NotificationStrategy.java
-
- Add notification test mode using debot
- If notification test mode is enabled, notifications will be displayed 5 sec after FAB check actions.
-
Before | After
:--: | :--:
=> Add notification test mode

app/src/main/res/layout/fragment_information.xml
none
According to the material design guidelines, view that can be clicked need touch feedback with ripple effect.
(In pre-lollipop, this setting is ignored.)
https://material.io/guidelines/motion/choreography.html#choreography-radial-reaction
Before | After
:--: | :--:
=> Add touch feedback to information icons with ripple

app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/ArrayRecyclerAdapter.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java
-
- This PR demonstrates the way to bind RecyclerView Adapter to `ObservableList`.
- Concept
- Fragment's role is just to set `ObservableList` to adapter at first. After set, fragment does nothing.
- In adapter's constructor, it add callback to `ObservableList`. In the callback, notify methods of RecyclerView are executed.
- `ContributorsViewModel` only add or remove items to `ObservableList`.
- Since this PR is just a suggestion (not strong opinion), it is up to you whether to merge.
-
Before | After
:--: | :--:
=> Refactoring contributors list

app/build.gradle, circle.yml
- none
- Update constraint layout to beta 5 released today
- https://sites.google.com/a/android.com/tools/recent/constraintlayoutbeta5isnowavailable
Before | After
:--: | :--:
=> Update Constraint Layout to beta 5

app/src/test/java/io/github/droidkaigi/confsched2017/util/LocaleUtilTest.kt
None
First I added the LocaleUtil tests.
Eventually I want to use [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP)  for date processing.
None
None
=> Add test for LocaleUtil.

app/src/main/java/io/github/droidkaigi/confsched2017/model/Topic.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/TopicColor.java, app/src/test/java/io/github/droidkaigi/confsched2017/viewmodel/TopicColorTest.kt
None
I used the order of enum as topic id.
- At first, dd tests.
- Add test for TopicColor. 1481b0f
- Remove unused constant values. d114220
- then, change style.
- Use order as topic id. fffb872
- Remove topic id field. 1d61fe9
None
None
=> Use the order of enum as topic id.

.idea/gradle.xml, app/src/main/assets/json/sponsors.json, app/src/main/assets/json/sponsors_en.json, app/src/main/java/io/github/droidkaigi/confsched2017/model/Sponsor.java, app/src/main/java/io/github/droidkaigi/confsched2017/model/Sponsorship.java, app/src/main/java/io/github/droidkaigi/confsched2017/util/AssetsUtil.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SponsorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SponsorViewModel.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SponsorshipViewModel.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SponsorshipsViewModel.java, app/src/main/res/drawable/rectangle_border_grey200.xml, app/src/main/res/layout/fragment_sponsors.xml, app/src/main/res/layout/view_sponsor_cell.xml, app/src/main/res/layout/view_sponsorship_cell.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
- #76 
- Displays sponsors from a localized JSON strings in the assets folder.
- Uses recyclever view to display a header and another recyclever to display sponsors.
- When a sponsor is clicked it loads their website in a webview.
- Tried to implement the design per the spec provided in #76 
-
Before | After
:--: | :--:
=> Implement view for displaying sponsors

app/build.gradle
- [#337 at droidkaigi2016](https://github.com/konifar/droidkaigi2016/issues/337)
In current calculation, the version code for the version name may be wrong.
Although it is not a fundamental solution, I think that it can be solved enough with this change. 🤔 
Before:
- 1.11.0 -> 210
- 2.1.0 -> 210
After:
- 1.11.0 -> 10110
- 2.1.0 -> 201000
none
none
=> Fix calculation of version code

app/src/main/assets/json/sponsors.json
- #200 
I copied sponsors category name from Droidkaigi website and paste to `assets/json/sponsors.json`.
- https://droidkaigi.github.io/2017/#sponsors
🍣  is also shown with no problem. (But it seems egg and salmon though webpage shows two tuna.)
I confirmed 🍣  is shown on API25 and API16.
Before | After
:--: | :--:
=> Translate sponsors.json into Japanese (Copied from Droidkaigi website).

app/src/main/java/io/github/droidkaigi/confsched2017/di/ActivityComponent.java
I think ActivityComponent inject method is too many.
My proposal is change argument type. 
<del>My proposal is use type parameter. Generic type parameter solves this issue.</del>
ActivityComponent inteface seems simply inject Activity instance.
But it's provides overload  methods each subclass :
```java
void inject(XXXActivity activity);
```
This approach cause increase method when Activity added.
I thought BaseActivity is boundary type for inject method in droidkaigi app.
So inject method definition is :
<del>
```java
T extends BaseActivity
```
</del>
```
void inject(BaseActivity activity);
```
Honestly, I want to use generic type parameter,but Dagger2 seems not allow it.
* Effective Java(Item 28: Use bounded wildcards to increase API flexibility. )
* [Dagger 2 Generic Type class inject …
=> change argument type(ActivityComponent#inject)

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchViewModel.java
- #224 
Close search result list when cover taped on search screen.
- add `SearchResultsAdapter#clearAllResults` and use it when cover taped.
- rename `Callback#close` to `Callback#closeSearchResultList`.
N/A
=> Close search result list when cover taped on search screen.

app/src/main/AndroidManifest.xml
- None
- Before: `ContributorsActivity` has "Sponsors" as label.  
Seems that is wrong.  
I think, "Contributors" is ok.
- None
None
By the way, we really need `android:label` property for not `LAUNCHER` Activity...?
https://developer.android.com/guide/topics/manifest/activity-element.html?hl=ja#label
=> fix wrong label

app/src/main/res/values/fonts.xml
- None
- Reduce lint error about "MissingTranslation".
I think, not needed translate about font file name.
So I add `translatable="false"`.
I really want, reduce all of error about "MissingTranslation". But I don't know about onesky...
- None
Before | After
:--: | :--:
=> remove lint error

app/src/main/java/io/github/droidkaigi/confsched2017/util/AppShortcutsUtil.java
Hi! It's a great app!
- None 
- A WrongConstant error occurred in `AppShortcutsUtil` when executing lint.
- The cause of this problem is the Gradle Plugins error.
- https://code.google.com/p/android/issues/detail?id=226891
- Therefore, I added `@SuppressLint ({"WrongConstant"})`.
- None 
Before | After
:--: | :--:
=> Fix WrongConstant error on lint.

app/build.gradle
#266 
Since some people now working on lint, let's add text report setting so that we can check the error in circle ci.
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.LintOptions.html#com.android.build.gradle.internal.dsl.LintOptions:textOutput
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.LintOptions.html#com.android.build.gradle.internal.dsl.LintOptions:textReport
Before | After
:--: | :--:
=> Enable lint text report

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/ContributorsActivity.java, app/src/main/res/menu/menu_contributors.xml, app/src/main/res/values/strings.xml
- https://github.com/DroidKaigi/conference-app-2017/issues/169
- Extract link url from list item.
- Add menu item for opening repository url.
This is same as you want..?
> remove the link from the description and add the link menu icon to the contributor page?
- None
Before | After
:--: | :--:
=> split repository link from list item

app/src/main/assets/json/sponsors_en.json
- #289 
- Change sushi to 🍣 at sponsors_en.json
- It's my first PR. Plz check this  🙇 
- https://github.com/DroidKaigi/conference-app-
2017/blob/master/app/src/main/assets/json/sponsors_en.json#L118
Before | After
:--: | :--:
=> change sushi to emoji

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionFeedbackActivity.java
None
- `SessionFeedbackViewModel` is not used in `SessionFeedbackActivity` so I have removed it's injection.
=> Remove unused SessionFeedbackViewModel injection.

app/src/main/java/io/github/droidkaigi/confsched2017/util/LocaleUtil.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SettingsFragment.java
- None
- `BinaryOperationInTimber` occurred when executing lint.
- This is caused by a [lint rule embedded in Timber](https://github.com/JakeWharton/timber#lint).
- Timber internally uses `String.format` to format log messages.
- Therefore, I changed the format of the log message to the way Timber recommends.
- None
Before | After
:--: | :--:
=> Fixed the output of the log message by Timber's recommended way.

app/src/main/res/drawable-v21/avd_add_to_check_24dp.xml, app/src/main/res/drawable-v21/avd_check_to_add_24dp.xml, app/src/main/res/drawable/avd_add_to_check_24dp.xml, app/src/main/res/drawable/avd_check_to_add_24dp.xml
- #266
- Ignore `MissingPrefix` lint error.
- This error is false detection of lint.
- Therefore, I added `tools: ignore = "MissingPrefix"`.
- None
Before | After
:--: | :--:
=> Ignore MissingPrefix error that occurs when lint is executed.

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/ContributorsActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/LicensesActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/MainActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SearchActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SponsorsActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/InformationFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SettingsFragment.java
none
Two kinds of methods of calling Activity exist in the current project.
First, `start` method in ContributorsActivity, MainActivity, SearchActivity and SponsorsActivity.
Second, `createIntent` method in SessionDetailActivity and SessionFeedbackActivity.
These should be unified into either.
I think it is better to use `createIntent` because it can use `Intent#addFrag` and `startActivityForResult` later... 🤔 
none
none
=> Unify method of calling Activity to `createIntent`

app/src/main/java/io/github/droidkaigi/confsched2017/di/ActivityComponent.java, app/src/main/java/io/github/droidkaigi/confsched2017/di/AppModule.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/ContributorsActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/helper/ResourceResolver.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ToolbarViewModel.java, app/src/main/res/layout/activity_contributors.xml, app/src/test/java/io/github/droidkaigi/confsched2017/util/RxTestSchedulerRule.kt, app/src/test/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModelTest.kt
None
The purpose of this PR is `ContributorsFragment` makes thin and `ContributorsViewModel` makes testable.
- Apply MVVM pattern to Toolbar title.
- Move logic (rendering contributors) from `ContributorsFragment` to `ContributorsViewModel`.
- Add tests for `ContributorsViewModel`.
=> More MVVM for Contributors view

app/src/test/java/io/github/droidkaigi/confsched2017/util/DateUtilTest.kt
None
Even if the DateUtil constructor does not throw an exception the original test succeeds.
I introduced ExpectedException.
None
None
=> Remove unnecessary test case.

app/src/main/res/layout/view_sessions_header_cell.xml
Prevent session cell click event triggered unexpectedly by tapping on header view.
- Nothing related
- Just a quick minor UI fix: tapping on the header view of session list causes click event on the cell behind. I don't think that is intended behavior.
- I just found #180, so this change might be a short life, though.
- None
Before | After
:--: | :--:
=> Ignore click events on session header

app/src/main/res/layout/view_search_result.xml
- #226 
- Replace to ConstraintLayout to view_search_result.xml
- Some layout modified ([discussed](https://github.com/DroidKaigi/conference-app-2017/issues/226#issuecomment-279210899))
- none
Before | After
:--: | :--:
=> Replace RelativeLayout to ConstraintLayout in "view_search_result.xml" and some layout fix

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SearchFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SearchResultViewModel.java, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
- None
- Animate search result items when the result changes. Please check screenshot gif.
- `RecyclerView.Adapter.setHasStableIds` is efficient for layout performance, and it's easy way to introduce item animation.
- For use above, SearchResultViewModel create id from session.id and which type of result (title, description, speaker).
- Set white color to background of the RecyclerView in search page. without this, the alpha animation looks not good.
This PR is just a suggestion, so close If you don't like it or don't need it.
- [RecyclerView.Adapter#setHasStableIds(boolean)](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#setHasStableIds(boolean))
Before | After
:--: | :--:
=> Animate search result items when the result changes.

app/src/main/res/values-v21/themes.xml, app/src/main/res/values/themes.xml
- none
- Apply theme color for Dialog
- Currently "AlertDialog" only used in "SettingsFragment"
- This dialog radio button and cancel button are using the system default color (looks like a green)
- I suggest using a theme color
- https://material.io/guidelines/components/dialogs.html#dialogs-specs
> Dialog actions use system colors by default, but they should reflect your product's color palette. Use a contrasting color, such as the palette’s accent color, to distinguish dialog actions from dialog content.
Material design guidelines suggest using accent colors, but the accent color of the current theme is red. Since this looks like a "warning" color, I suggest a theme color.
If do not need the this PR, please close it!
Before | After
:--: | :--:
=> Apply theme color for Dialog (Suggest)

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SettingsFragment.java, app/src/main/res/values-v21/themes.xml, app/src/main/res/values/themes.xml
- none
- Related #324 
- Sorry it has become an separate PR
- Currently to using the system framework's AlertDialog widget in change language dialog
- This widget is NOT provide Material Design dialog for under Android 4.4
- Replace to support-v7 version's AlertDialog
- If don't need the this PR, please close it
- none
Before (4.1) | After (4.1) | Before (4.4) | After (4.4) | Before (7.1) | After (7.1)
:--: | :--: | :--: | :--: | :--: | :--:
=> Replace for system framework's "AlertDialog" to "support-v7 AlertDialog"

app/build.gradle
-
~~There are 2 packagingOptions in `app/build.gradle`. Let's combine them.~~
~~BTW, do we really need `exclude 'LICENSE.txt'`???~~ 
Remove unnecessary `packagingOptions`
-
Before | After
:--: | :--:
=> Remove unnecessary packagingOptions

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java
- Avoid calling getContext() after fragment detached
=> Avoid NullPointerException on showing toast

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SplashActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SplashFragment.java, app/src/main/res/layout/activity_splash.xml, app/src/main/res/layout/fragment_splash.xml
Currently SplashActivity has 2 responsibility:
* animating ParticleView
* start MainActivity with 3 seconds delay.
I think it would be more useful if the logic of animation is capsulized in a Fragment.
This Pull Request provides `SplashFragment` for handling the ParticleView, and makes SplashActivity simpler.
-
not changed. Just a refactoring :)
=> Separate the logic for animating the ParticleView into SplashFragment.

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java, app/src/main/res/values-land/integers.xml, app/src/main/res/values-sw600dp/integers.xml, app/src/main/res/values/integers.xml
none
- I changed the contributors columns count from 3 to 6 when the device is landscape or tablet.
- https://developer.android.com/guide/practices/screens_support.html
landscape
Before | After
:--: | :--:
tablet
Before | After
:--: | :--:
=> Apply contributors columns to landscape and tablets

app/src/main/java/io/github/droidkaigi/confsched2017/service/DebugOverlayService.java
- DebugOverlayService should live along with an app process and never be restarted again automatically after its death, causing unnecessary process restart 😭
=> Stop restarting a process for service recreation

app/src/main/res/drawable/bg_splash.xml, app/src/main/res/values-v19/themes.xml, app/src/main/res/values-v21/themes.xml, app/src/main/res/values/colors_palette.xml, app/src/main/res/values/themes.xml
none
A white screen is displayed until the inflation of Splash layout is completed. "background" attribute of the theme can solve this problem.
I created a splash-like drawable with xml, but it's not perfect. 😢 Please close this PR if you feel unnecessary 🙇 
none
Before | After
:--: | :--:
=> Start splash more quickly

app/src/main/java/io/github/droidkaigi/confsched2017/di/ActivityComponent.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SplashActivity.java
- https://github.com/DroidKaigi/conference-app-2017/issues/321
`SplashActivity` is displayed at minimum 1500 millisecond.
For that, I am generating `delaySingleSource`.
But I do not know if this is the best. 🤔
Please opinion if there is something.  🙇
none
=> Session loading in Splash

app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java, app/src/main/res/layout/fragment_contributors.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
none
Loading will result in an error if you do not have a cache and can't connect to the Internet, but nothing changes on the screen.
In that case, I think that the application needs an approach such as showing a retry button.
I implemented it on ContributorsFragment for the time being, I think that the similar processing is necessary on other screens.
But since they are numerous, we will create an Issue if necessary 🙇 
none
Before | After
:--: | :--:
=> Implement a retry button for when contributors load failed

app/src/main/res/layout/fragment_my_sessions.xml
- #353 
- Use `match_parent` instead `wrap_content` for RecyclerView which has fixed size.
- None
Before | After
:--: | :--:
=> Use match_parent for my sessions recycler view.

app/src/main/res/layout/fragment_session_detail.xml, app/src/main/res/values/styles_session.xml
- #336 
- Remove shadow from session title.
- Add black alpha tint to background image. (Is it correct?)
None
Before | After (upper: 12, lower: 30)
:--: | :--:
&nbsp;  | <img src="https://cloud.githubusercontent.com/assets/1498691/23066839/d50c1508-f55f-11e6-874b-d09070664a63.png" width="300" />
=> Fix doubled session title

app/src/main/AndroidManifest.xml, app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/OverScrollLayout.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionDetailFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionDetailViewModel.java, app/src/main/res/layout/fragment_session_detail.xml, app/src/main/res/values/themes.xml
- https://github.com/DroidKaigi/conference-app-2017/issues/228
- Finish SessionDetailActivity when page overscrolled
- none
Before | After
:--: | :--:
=> Add page finishing function when over scrolled to SessionDetailActivity

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/ContributorsActivity.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/ContributorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/ContributorsViewModel.java
none
Good evening!
I made use of `ChromeCustomTabs` to show the web in `ContributorsActivity` using `Navigator`.
BTW, I think that you should go to the [Contributors page of GitHub](https://github.com/DroidKaigi/conference-app-2017/graphs/contributors), because the current URL is the same as the Infomation icon link 🤔 💭 
What do you think?
none
none
=> Use ChromeCustomTabs in ContributorsActivity

app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/ParticlesAnimationView.java
- https://github.com/DroidKaigi/conference-app-2017/issues/365
- Create new Stream instance every time 'onDraw' is called.
- So using 'for' statement.
- none
=> Using the 'for' statement instead of create new Stream instance.

circle.yml
- #266
- Introducing [reviewdog](https://github.com/haya14busa/reviewdog), lint notifier.
- As stated in #266, you need a GitHub personal access token to use reviewdog.
- With this setup, reviewdog will swallow all stdout lint result. If you want to check actual result on CircleCI's build page, I'm going update PR to use xml output instead.
- https://github.com/haya14busa/reviewdog
- https://circleci.com/docs/fork-pr-builds/#security-implications-of-running-builds-for-pull-requests-from-forks
Before | After
:--: | :--:
=> add reviewdog configuration

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SplashActivity.java
none
Since the app has no error handling in `loadSessionsForCache()`, it crashes when fails to load sessions in splash. 💥 
I added only logs using Timber.
I think that we need to implement session reloading function in the future.
none
none
=> Fix crash in splash when offline

circle.yml
- https://circleci.com/gh/DroidKaigi/conference-app-2017/679
- Sometimes circleci fail to fetch branches correctly, so I added fetch command expressly
- None
=> Added explicit git-fetch to ci commands

app/build.gradle, app/licenses.yml, app/src/main/java/io/github/droidkaigi/confsched2017/di/AppModule.java
I have updated retrofit library version 2.1.0 -> 2.2.0.
This allows us to remove Jake's retrofit2-rxjava2-adapter dependency as retrofit itself now officially supports rxjava2-adapter. :eagle: 
reference: https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-220-2017-02-21
=> Update retrofit 2.1.0 -> 2.2.0

app/src/main/res/values-v21/themes.xml
[This change](https://github.com/DroidKaigi/conference-app-2017/pull/359) caused the color of the status bar to be `dark_theme`.
I fixed the appearance by making it transparent for post-Lollipop. 🌀 
Before | After
:--: | :--:
=> Make the status bar transparent on SessionDetailActivity

app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/ArrayRecyclerAdapter.java
#358
Remove `Iterator` interface from `ArrayRecyclerAdapter`
-
Before | After
:--: | :--:
=> Remove Iterator interface

app/src/main/java/io/github/droidkaigi/confsched2017/receiver/NotificationReceiver.java
- 
- Fixed an issue that group notification remains even if notification is tapped.
-
Before | After
:--: | :--:
=> Fixed an issue that group notification remains

app/src/test/java/io/github/droidkaigi/confsched2017/repository/contributors/ContributorsLocalDataSourceTest.kt
None
- Ignore the unstable test `ContributorsLocalDataSourceTest#updateAllAsyncAsInsert` which is added in #362 by me 🙇 🙇 
I think this problem is caused by scheduler operation of Rx, but I cannot solve yet since this test always passes in my local env.
Of course the best scenario is that makes this test stable, but now I just added `@Ignore` annotation 😭
=> Ignore unstable test

circle.yml
Circle CI informs us that test metadata are not found.
(see a screenshot below)
- JUnit XML files are copied from `app/build/test-results/` to `$CIRCLE_TEST_REPORTS/junit/`
- https://circleci.com/docs/1.0/test-metadata/#gradle-junit-results
=> Tweak circle.yml to collect test metadata.

app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SplashActivity.java
#377
It seems `android:noHistory="true"` doesn't finish the activity if user tap back button right after launching new activity.
I couldn't find this behavior's documentation. 
Could anyone point me if there is other concern?
I tried the following code 
```java
private void loadSessionsForCache() {
//        Disposable disposable = Single.zip(sessionsRepository.findAll(Locale.getDefault()),
//                mySessionsRepository.findAll(),
//                Single.timer(MINIMUM_LOADING_TIME, TimeUnit.MILLISECONDS),
//                (sessions, mySessions, obj) -> Observable.empty())
//                .subscribeOn(Schedulers.io())
//                .observeOn(AndroidSchedulers.mainThread())
//                .doFinally(() -> {
//                    if (isFinishing()) return;
// …
```
=> Finish splash activity manually

app/build.gradle, circle.yml
- none
- Constraint Layout 1.0.1 is released today!
- https://sites.google.com/a/android.com/tools/recent/constraintlayout101isnowavailable
Before | After
:--: | :--:
=> Update ConstraintLayout to 1.0.1

app/src/main/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClient.java, app/src/main/java/io/github/droidkaigi/confsched2017/api/service/GoogleFormService.java, app/src/main/java/io/github/droidkaigi/confsched2017/model/SessionFeedback.java, app/src/main/java/io/github/droidkaigi/confsched2017/repository/feedbacks/SessionFeedbackRemoteDataSource.java, app/src/main/java/io/github/droidkaigi/confsched2017/view/fragment/SessionFeedbackFragment.java, app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionFeedbackViewModel.java, app/src/main/res/layout/fragment_session_feedback.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles_base.xml, app/src/test/java/io/github/droidkaigi/confsched2017/api/DroidKaigiClientTest.kt
https://github.com/DroidKaigi/conference-app-2017/issues/74
Just created session feedback page.
- Prevent double tap.
- Show success message properly.
- Handle submit error.
- Handle network error.
- Show error message when there are empty values.
English | Japanese
:--: | :--:
=> Created session feedback page

app/src/main/AndroidManifest.xml
- #409 
- MainActivity's instance is re-created many times because there are no launch mode specified. 
- We can overlap the same MainActivity eternally. 
- [ActivityのlaunchModeの効果的な使い方](http://qiita.com/kskso9/items/1ee5b1dbe996402ae94b)
- Launch App from Home
- press the OS home button
- Launch App from the icon again. 
- press the OS back button. 
nothing but test manually
=> adapt launch mode = singleTask for MainActivity
